version = 0.1
[default.deploy.parameters]
stack_name = "rate-limit-monitoring"
resolve_s3 = true
s3_prefix = "rate-limit-monitoring"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AssumeRoleHandler=\"main\" AssumeWebIdentityHandler=\"main\""
image_repositories = []
