version = 0.1
[default.deploy.parameters]
stack_name = "geras-rate-limit"
resolve_s3 = true
s3_prefix = "geras-rate-limit"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AssumeRoleHandler=\"main\" AssumeWebIdentityHandler=\"main\""
image_repositories = []
